# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    stella_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    stella_gripper_controller:
      type: position_controllers/GripperActionController


stella_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - base_link-link1
      - link1-link2
      - link2-link3

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

stella_gripper_controller:
  ros__parameters:
    action_monitor_rate: 200.0
    joint: link8-link9
    goal_tolerance: 0.01
    max_effort: 0.05
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0
    gains:
      gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}


joint_state_broadcaster:
   ros__parameters:
      #use_local_topics: True
      joints:
        - base_link-link1
        - link1-link2
        - link2-link3
        - link8-link9
      interfaces:
         - position
         - velocity
